export const brotherhood = [
    {
        avatar: "https://avatars.githubusercontent.com/u/4670056?v=4",
        title: "Anthony",
        url: "https://www.youtube.com/@anthonygg_/",
        repoUrl: "https://github.com/anthdm/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/24481316?v=4",
        title: "Sub-J",
        url: "",
        repoUrl: "https://github.com/sapjarern/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/88017471?v=4",
        title: "Ninja",
        repoUrl: "https://github.com/chaninlaw/",
        url: "https://chaninlaw.vercel.app/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/57356777?v=4",
        title: "Phoon",
        url: "",
        repoUrl: "https://github.com/phoon-phoon/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/132638455?v=4",
        title: "Tum",
        url: "https://nuttapat-portfolio.onrender.com/",
        repoUrl: "https://github.com/nuttapat-swd",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/77603903?v=4",
        title: "Fluke",
        url: "https://jeerawut.vercel.app/",
        repoUrl: "https://github.com/jeerawut97/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/103378900?v=4",
        title: "Gug",
        url: "https://bt144p-portfolio.vercel.app/",
        repoUrl: "https://github.com/B144p/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/56217133?v=4",
        title: "Ohm",
        url: "",
        repoUrl: "https://github.com/OmTanakorn/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/144673048?v=4",
        title: "Macc",
        url: "",
        repoUrl: "https://github.com/MacFF/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/82906183?v=4",
        title: "Aebalz",
        url: "",
        repoUrl: "https://github.com/aebalz/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/100982491?v=4",
        title: "Bright",
        url: "",
        repoUrl: "https://github.com/Boonyarit-siol/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/92322801?v=4",
        title: "Fern",
        url: "",
        repoUrl: "https://github.com/L4zy-p/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/97378030?v=4",
        title: "Sorn",
        url: "",
        repoUrl: "https://github.com/NakLast/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/74338674?v=4",
        title: "Ken",
        url: "",
        repoUrl: "https://github.com/Chaiwat-S-dev/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/81948142?v=4",
        title: "Aek",
        url: "",
        repoUrl: "https://github.com/arthit666/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/125941041?v=4",
        title: "Keng",
        url: "",
        repoUrl: "https://github.com/Ke24gPongsathon/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/139423958?v=4",
        title: "Nick",
        url: "",
        repoUrl: "https://github.com/Anurak-DA/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/69451462?v=4",
        title: "Kwan",
        url: "",
        repoUrl: "https://github.com/kncode74/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/85872878?v=4",
        title: "Bank",
        url: "",
        repoUrl: "https://github.com/bankvery007/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/36122938?v=4",
        title: "Mr.Ball",
        url: "",
        repoUrl: "https://github.com/hibiki0ai/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/112603678?v=4",
        title: "Jes",
        url: "",
        repoUrl: "https://github.com/natchaSWD/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/141224527?v=4",
        title: "Pat",
        url: "",
        repoUrl: "https://github.com/PatSwiftD/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/146170468?v=4",
        title: "Pam",
        url: "",
        repoUrl: "https://github.com/PamPattarit/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/148047498?v=4",
        title: "Yok",
        url: "",
        repoUrl: "https://github.com/YokNaron/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/169340142?v=4",
        title: "Auon",
        url: "",
        repoUrl: "https://github.com/Whatchawrawit/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/144302840?v=4",
        title: "Yo",
        url: "",
        repoUrl: "https://github.com/NuttaphonK/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/169340142?v=4",
        title: "Mek",
        url: "",
        repoUrl: "https://github.com/Whatchawrawit/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/46487715?v=4",
        title: "God Koe",
        url: "",
        repoUrl: "https://github.com/5A681/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/118100445?v=4",
        title: "Tommy",
        url: "",
        repoUrl: "https://github.com/emmitt-k/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/123813313?v=4",
        title: "Force",
        url: "https://force-naphat-portfolio-sigma.vercel.app/",
        repoUrl: "https://github.com/force445/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/187376798?v=4",
        title: "Park",
        url: "https://park-surakiat.vercel.app/",
        repoUrl: "https://github.com/SurakiatP/",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/169155544?v=4",
        title: "Ram",
        url: "https://iamrams.netlify.app/",
        repoUrl: "https://github.com/iamrams92",
        description: "",
    },
    {
        avatar: "https://avatars.githubusercontent.com/u/91175644?v=4",
        title: "Safe",
        url: "",
        repoUrl: "https://github.com/PS-safe",
        description: "",
    },
];

if (import.meta.env.DEV) {
    brotherhood.push({
        avatar: "https://avatars.githubusercontent.com/u/168957872?v=4",
        title: "Anonymous",
        url: "",
        repoUrl: "https://github.com/0xtokiya/",
        description: "",
    });
}
