export const RESEARCH_PAPERS = [
    {
        id: "001-unified-state",
        title: "System Design X: The Unified State Architecture",
        abstract: "A philosophical and technical exploration into reducing system entropy by unifying client-server state management. This research challenges the traditional separation of concerns in favor of a holistic 'One State' model.",
        problemFraming: "Modern web development suffers from 'State Fragmentation'—where data exists in multiple inconsistent copies (DB, API Cache, UI State). This leads to 40% of frontend bugs being synchronization errors.",
        hypothesis: "If we treat the entire distributed system as a single state machine where the frontend is merely a 'View' projection of the backend state, we can eliminate synchronization logic entirely.",
        limitations: "Network latency makes 'pure' projection impossible without optimistic UI. The sheer size of state requires intelligent partial subscription models.",
        futureWork: "Prototype a Rust-based WASM sync engine that maintains a partial replica of the Postgres WAL in the browser.",
        date: "2025-01-20",
        version: "v0.9.0 (Draft)",
        author: "Puritat Chamart",
        tags: ["System Architecture", "State Management", "Distributed Systems"],
        citation: "Chamart, P. (2025). System Design X.",
        status: "In Progress",
        readTime: "20 min read",
        downloadUrl: "#",
        previewUrl: "#"
    },
    {
        id: "002-trustless-coordination",
        title: "Trustless Coordination Patterns in Human Systems",
        abstract: "Investigating how cryptographic primitives can replace middle-management in software teams. A study on DAO-like structures applied to corporate hierarchies.",
        problemFraming: "Human coordination typically requires a 'Trusted Coordinator' (Manager) to resolve conflicts and allocate resources. This introduces single points of failure and bias.",
        hypothesis: "Smart contracts can automate the 'Management Layer' of software delivery—allocating bounties, verifying code quality via ZK-proofs of test passing, and distributing equity per commit.",
        limitations: "The 'Oracle Problem' of assessing creative work quality remains unsolved. Code coverage is not a proxy for code value.",
        futureWork: "Develop a 'Proof of Value' metric that combines Git activity, peer review sentiment, and production impact metrics.",
        date: "2024-12-15",
        version: "v1.2.1",
        author: "Puritat Chamart",
        tags: ["DAO", "Game Theory", "Organizational Design"],
        citation: "Chamart, P. (2024). Trustless Coordination.",
        status: "Published",
        readTime: "15 min read",
        downloadUrl: "#",
        previewUrl: "#"
    },
    {
        id: "003-minimal-backend",
        title: "Minimal Backend Thesis",
        abstract: "Proposing a radical reduction in backend complexity by leveraging edge computing and smart database policies. The 'Backend' should fade into infrastructure.",
        problemFraming: "We spend 60% of engineering time writing 'Glue Code' (API endpoints, DTOs, Controllers) that simply moves data from A to B without adding value.",
        hypothesis: "A 'Thick Database, Thick Client' architecture (using RLS and Edge Functions) allows us to delete the application server layer entirely for 90% of CRUD apps, reducing TCO by half.",
        limitations: "Security rules become complex to test. Business logic that requires global context (e.g., aggregate analytics) is hard to implement in Row Level Security.",
        futureWork: "Benchmark a 'Serverless SQL' stack against a traditional NestJS microservices cluster under high load.",
        date: "2024-11-10",
        version: "v1.0.0",
        author: "Puritat Chamart",
        tags: ["Backend", "Serverless", "Edge Computing"],
        citation: "Chamart, P. (2024). Minimal Backend Thesis.",
        status: "Published",
        readTime: "18 min read",
        downloadUrl: "#",
        previewUrl: "#"
    }
];
